package com.blinnproject.myworkdayback.model;

public enum EMuscle {
  PECTORALIS_MAJOR,
  FINGER_FLEXORS,
  DELTOID,
  TRICEPS,
  ABDOMINALS,
  GASTROCNEMIUS,
  SARTORIUS,
  ABDUCTORS,
  STERNOCLEIDOMASTOID,
  QUADRICEPS,
  BRACHIORADIALIS,
  TRAPEZIUS,
  BICEPS,
  PERONEUS_LONGUS,
  EXTERNAL_OBLIQUE,
  ABSUCTORS,
  TIBIALIS_ANTERIOR,
}
