CREATE SEQUENCE IF NOT EXISTS password_reset_token_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS refresh_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE exercise
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by      BIGINT,
    last_updated_by BIGINT,
    created_on      TIMESTAMP WITHOUT TIME ZONE,
    last_updated_on TIMESTAMP WITHOUT TIME ZONE,
    is_active       BOOLEAN                                 NOT NULL,
    name            VARCHAR(150)                            NOT NULL,
    CONSTRAINT pk_exercise PRIMARY KEY (id)
);

CREATE TABLE exercise_muscle
(
    exercise_id BIGINT NOT NULL,
    muscle_used VARCHAR(255)
);

CREATE TABLE password_reset_token
(
    id          BIGINT                      NOT NULL,
    user_id     BIGINT,
    token       VARCHAR(255)                NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    attempts    INTEGER,
    CONSTRAINT pk_password_reset_token PRIMARY KEY (id)
);

CREATE TABLE profile_picture
(
    user_id   BIGINT NOT NULL,
    name      VARCHAR(255),
    type      VARCHAR(255),
    file_data BYTEA,
    CONSTRAINT pk_profile_picture PRIMARY KEY (user_id)
);

CREATE TABLE refresh_token
(
    id          BIGINT                      NOT NULL,
    user_id     BIGINT,
    token       VARCHAR(255)                NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE schedule
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by       BIGINT,
    last_updated_by  BIGINT,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    last_updated_on  TIMESTAMP WITHOUT TIME ZONE,
    is_active        BOOLEAN                                 NOT NULL,
    start_date       date,
    end_date         date,
    start_time       time WITHOUT TIME ZONE,
    end_time         time WITHOUT TIME ZONE,
    frequency        VARCHAR(255),
    monday           BOOLEAN,
    tuesday          BOOLEAN,
    wednesday        BOOLEAN,
    thursday         BOOLEAN,
    friday           BOOLEAN,
    saturday         BOOLEAN,
    sunday           BOOLEAN,
    workout_model_id BIGINT,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by              BIGINT,
    last_updated_by         BIGINT,
    created_on              TIMESTAMP WITHOUT TIME ZONE,
    last_updated_on         TIMESTAMP WITHOUT TIME ZONE,
    is_active               BOOLEAN                                 NOT NULL,
    username                VARCHAR(20)                             NOT NULL,
    gender                  SMALLINT,
    email                   VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    profile_picture_user_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE workout
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workout_type           VARCHAR(31),
    created_by             BIGINT,
    last_updated_by        BIGINT,
    created_on             TIMESTAMP WITHOUT TIME ZONE,
    last_updated_on        TIMESTAMP WITHOUT TIME ZONE,
    is_active              BOOLEAN                                 NOT NULL,
    name                   VARCHAR(255),
    description            VARCHAR(255),
    workout_model_id       BIGINT,
    session_status         VARCHAR(255),
    started_at             TIMESTAMP WITHOUT TIME ZONE,
    ended_at               TIMESTAMP WITHOUT TIME ZONE,
    sport_preset           VARCHAR(255),
    has_warm_up            BOOLEAN,
    has_stretching         BOOLEAN,
    icon_name              VARCHAR(255),
    icon_hexadecimal_color VARCHAR(255),
    CONSTRAINT pk_workout PRIMARY KEY (id)
);

CREATE TABLE workout_exercise
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by             BIGINT,
    last_updated_by        BIGINT,
    created_on             TIMESTAMP WITHOUT TIME ZONE,
    last_updated_on        TIMESTAMP WITHOUT TIME ZONE,
    is_active              BOOLEAN                                 NOT NULL,
    position_index         INTEGER                                 NOT NULL,
    perform_status         SMALLINT,
    workout_id             BIGINT,
    exercise_id            BIGINT,
    notes                  VARCHAR(255),
    number_of_warm_up_sets INTEGER,
    CONSTRAINT pk_workout_exercise PRIMARY KEY (id)
);

CREATE TABLE workout_sets
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by          BIGINT,
    last_updated_by     BIGINT,
    created_on          TIMESTAMP WITHOUT TIME ZONE,
    last_updated_on     TIMESTAMP WITHOUT TIME ZONE,
    is_active           BOOLEAN                                 NOT NULL,
    position_index      INTEGER                                 NOT NULL,
    is_performed        BOOLEAN,
    weight              INTEGER,
    rest_time           VARCHAR(255),
    notes               VARCHAR(255),
    reps_count          INTEGER,
    workout_exercise_id BIGINT,
    CONSTRAINT pk_workout_sets PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_6f43907a5d90e52ae34c98a75 UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_fa186aaf68519427debd77e9b UNIQUE (email);

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_password_reset_token_user UNIQUE (user_id);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_token UNIQUE (token);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_user UNIQUE (user_id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE profile_picture
    ADD CONSTRAINT FK_PROFILE_PICTURE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE schedule
    ADD CONSTRAINT FK_SCHEDULE_ON_WORKOUT_MODEL FOREIGN KEY (workout_model_id) REFERENCES workout (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PROFILEPICTURE_USER FOREIGN KEY (profile_picture_user_id) REFERENCES profile_picture (user_id);

ALTER TABLE workout_exercise
    ADD CONSTRAINT FK_WORKOUT_EXERCISE_ON_EXERCISE FOREIGN KEY (exercise_id) REFERENCES exercise (id);

ALTER TABLE workout_exercise
    ADD CONSTRAINT FK_WORKOUT_EXERCISE_ON_WORKOUT FOREIGN KEY (workout_id) REFERENCES workout (id);

ALTER TABLE workout
    ADD CONSTRAINT FK_WORKOUT_ON_WORKOUT_MODEL FOREIGN KEY (workout_model_id) REFERENCES workout (id);

ALTER TABLE workout_sets
    ADD CONSTRAINT FK_WORKOUT_SETS_ON_WORKOUT_EXERCISE FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercise (id);

ALTER TABLE exercise_muscle
    ADD CONSTRAINT fk_exercise_muscle_on_exercise FOREIGN KEY (exercise_id) REFERENCES exercise (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);